<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataweb" nsURI="http://www.example.org/dataweb" nsPrefix="dataweb">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Aplicacion">
    <eAnnotations source="DSLDoc">
      <details key="Author" value="Sergio Terrazas Lobato y Javier Costillo Palacios"/>
      <details key="Last update" value="19/04/2025"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Rol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redessociales" upperBound="-1"
        eType="#//RedSocial" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paginapantallas" lowerBound="1"
        upperBound="-1" eType="#//PaginaPantalla" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedatos" upperBound="-1"
        eType="#//BaseDatos" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseDatos">
    <eAnnotations source="DSLDoc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablas" lowerBound="1"
        upperBound="-1" eType="#//Entidad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad">
    <eAnnotations source="DSLDoc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidadRefereenciada" upperBound="-1"
        eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usuarios" lowerBound="1"
        upperBound="-1" eType="#//Rol" eOpposite="#//Rol/entidades"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eAnnotations source="DSLDoc"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TipoAtributo" eType="#//TipoAtributo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrimaryKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrearInstancia" eSuperTypes="#//DependienteDeEntidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndiceExtendido" eSuperTypes="#//Indice"/>
  <eClassifiers xsi:type="ecore:EClass" name="DetallesInstancia" eSuperTypes="#//DependienteDeEntidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActualizacionInstancia" eSuperTypes="#//DependienteDeEntidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndiceEntidad" eSuperTypes="#//Indice"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndiceDetalle" eSuperTypes="#//Indice"/>
  <eClassifiers xsi:type="ecore:EClass" name="BorradoInstancia" eSuperTypes="#//DependienteDeEntidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cuestionario" eSuperTypes="#//Interactiva">
    <eAnnotations source="DSLDoc"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Evaluado" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preguntasC" lowerBound="1"
        upperBound="-1" eType="#//Pregunta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pregunta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tipo" eType="#//TipoPregunta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respuestas" upperBound="-1"
        eType="#//Respuesta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Texto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rcorrecta" lowerBound="1"
        eType="#//Respuesta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependienteDeEntidad" abstract="true"
      eSuperTypes="#//PaginaPantalla"/>
  <eClassifiers xsi:type="ecore:EClass" name="Normal" eSuperTypes="#//PaginaPantalla">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Contenido" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contenidomultimedia" upperBound="-1"
        eType="#//ContenidoMultimedia" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Encuesta" eSuperTypes="#//Interactiva">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preguntasE" lowerBound="1"
        upperBound="-1" eType="#//Pregunta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interactiva" abstract="true" eSuperTypes="#//PaginaPantalla">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoPregunta">
    <eLiterals name="OpcionMultiple"/>
    <eLiterals name="V_F" value="1"/>
    <eLiterals name="Corta" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Respuesta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Texto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" upperBound="-1"
        eType="#//Entidad" eOpposite="#//Entidad/usuarios"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accesoapaginapantalla"
        upperBound="-1" eType="#//PaginaPantalla" eOpposite="#//PaginaPantalla/usuario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedSocial">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paginapantalla" upperBound="-1"
        eType="#//PaginaPantalla" eOpposite="#//PaginaPantalla/redsocial"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Indice" abstract="true" eSuperTypes="#//DependienteDeEntidad">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Atributos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContenidoMultimedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaPantalla" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" lowerBound="1"
        upperBound="-1" eType="#//Rol" eOpposite="#//Rol/accesoapaginapantalla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redsocial" upperBound="-1"
        eType="#//RedSocial" eOpposite="#//RedSocial/paginapantalla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidad" lowerBound="1"
        eType="#//Entidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index" eSuperTypes="#//PaginaPantalla"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoAtributo">
    <eLiterals name="Integer"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="String" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CRUD" eSuperTypes="#//DependienteDeEntidad"/>
</ecore:EPackage>
